# Name the application the same as in your .platform.app.yaml.
name: back-drupal
# Use the recipe appropriate for your application.
recipe: drupal8

config:
  # Lando defaults to Apache. Switch to nginx to match Platform.sh.
  via: nginx
  # Set the webroot to match your .platform.app.yaml.
  webroot: web
  database: mysql:5.7